version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80" # Map port 8000 on host to port 80 in the container
    volumes:
      - .:/var/www/html # Mount project directory inside the container
